# name: padellers-frontend

# static_sites:
# - name: frontend
#   github:
#     repo: alvaroprtm/padellers-ecommerce-frontend
#     branch: main
#   build_command: npm install && npm run build
#   output_dir: dist

#   envs:
#   - key: VITE_API_URL
#     value: "https://padellers-back-cdnso.ondigitalocean.app/"

#   # Explicit SPA routes configuration - fixes login/register 404s
#   routes:
#   - path: /
#   - path: /login
#   - path: /register
#   - path: /products
#   - path: /cart
#   - path: /orders
#   - path: /product/*

#   # Fallback for all other routes
#   catchall_document: index.html
#   # error_document: index.html

#   # Headers for better caching and CORS
#   headers:
#   - pattern: "*.js"
#     set:
#       Cache-Control: "public, max-age=31536000, immutable"
#   - pattern: "*.css"
#     set:
#       Cache-Control: "public, max-age=31536000, immutable"
