name: padellers-frontend

static_sites:
- name: frontend
  github:
    repo: alvaroprtm/padellers-ecommerce-frontend
    branch: main
  build_command: npm install && npm run build
  output_dir: dist
  envs:
  - key: VITE_API_URL
    value: "https://padellers-back-cdnso.ondigitalocean.app/"
  routes:
  - path: /
  catchall_document: index.html
  error_document: index.html
